#!/usr/bin/env bash
# This bash script transfers a file from our client to a server

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
SCP_OPTIONS="-o StrictHostKeyChecking=no"

if [ "$#" -lt 4 ]; then
	scp $SCP_OPTIONS -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
elif [ "$#" -lt 3]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi

