#!/usr/bin/env bash
# This Bash script that configures a new Ubuntu machine to respect above requirements 
# ...(this script will be run on the server itself)
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start