#!/usr/bin/env bash
# This Bash script that configures a new Ubuntu machine to respect above requirements 
# ...(this script will be run on the server itself)

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
if systemctl is-active --quiet nginx; then
    echo "Nginx is now installed, configured, and running."
else
    echo "Nginx failed to start. Please check the configuration."
fi
