#!/usr/bin/env bash
# Configure a brand new Ubuntu machine so that its HTTP response
# ...contains a custome header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed i "15i \\\tadd_header X-Served-By 1574-web-01;" /etc/nginx/nginx.conf
sudo service nginx restart