#!/usr/bin/env bash
# This bash script installs and configures HAproxy on your lb-01 server
apt-get -y update
apt-get -y install haproxy
echo "frontend webapp
        bind *:80
		mode http
		default_backend webapp_backend
    backend webapp_backend
	    balance roundrobin
		server 299593-web-01 34.224.4.34:80 check
		server 299593-web-02 18.204.13.28:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
service haproxy restart