#!/usr/bin/env bash
#Bash script that manages 'manage_my_process'

process_start()
{
	if [ ! -f "/var/run/my_process.pid" ]
	then
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
	fi
}

process_stop()
{
	if [ ! -f "/var/run/my_process.pid" ]
        then
		echo "manage_my_process stopped"
		kill "$(cat /var/run/my_process.pid)"
		rm -f /var/run/my_process.pid
	fi
}

process_restart()
{
	process_stop
	process_start
	echo "manage_process restarted"
}

case "$1" in
	start)
		process_start
		;;
	stop)
		process_stop
		;;
	restart)
		process_restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
