#!/usr/bin/env bash
#Bash script that displays the content of the file "/etc/passwrd"
#using while loop + IFS

while IFS=':' read -r username _ uid gid info home shell; do

	user_info=$(echo "$info" | sed 's/^ *//;s/ *$//')
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $user_info"
done < /etc/passwd
