#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with:
#local hosts resolved to 127.0.0.2
#facebook.com resolved to 8.8.8.8

hosts_file="/etc/hosts"
hosts_file_new="$HOME/hosts.new"

cp "$hosts_file" "$hosts_file_new"
echo "127.0.0.2 	localhost" > "$hosts_file_new"
echo "8.8.8.8		facebook.com" >> "$hosts_file_new"
cp -f "$hosts_file_new" "$hosts_file"
